### ISSUE TITLE
More reasonable error message if terraform fmt fails

### ISSUE THREAD

**Issue by egrimstad** [entur/gha-terraform#63]
![image](https://github.com/user-attachments/assets/c9c5fd90-3fc6-4445-8834-1719bc32384d)

When terraform fmt fails it is somewhat difficult to see what you should do to fix it, as it just outputs the list of files that are not formatted correctly. Would be nice if there was some kind of helpful error message that told the user what was wrong and what they can do to fix the error.

**Comment by AlexanderBrevig** [comment]
Something like

> Please run `terraform fmt` 

then?

**Comment by Glenn-Terjesen** [comment]
in this example you have not run `terraform fmt` on the terraform code.
Tip, you can do this automatically in Ms Code and probably in intellij as well. 

Terraform Format output detected errors with the following files:
blabla.tf

Please run `terraform fmt`
